# Generated by Django 5.2.8 on 2026-05-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='distance',
        ),
    ]
