import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/providers";
import Navbar from "./components/Navbar";
import Logo from "@/public/vercel.svg"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Y-car rental site",
  description: "Generated by create next app",
  // images: [
  //    {
  //       url: Logo.src, //to fill logo
  //       width: 1200,
  //       height: 630,
  //       alt: "Room",
  //     },
  // ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
        <Navbar />
          {children}

        </QueryProvider>
      </body>
    </html>
  );
}
